spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 1000
            read-timeout: 2000
          service-product:
            connect-timeout: 3000
            read-timeout: 5000
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
#            retryer:
#            response-interceptor: com.cloud.order.interceptor.TokenRequestInterceptor
feign:
  sentinel:
    enabled: true