server:
  port: 8001
spring:
  profiles:
    active: test
  application:
    name: service-product
  cloud:
    nacos:
      server-addr: 192.168.255.128:8848
      config:
        #若不配置spring.profiles.active 则默认使用冒号后面的public
        namespace: ${spring.profiles.active:public}
        import-check:
          enabled: false
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
---
spring:
  config:
    import:
      - nacos:common.properties?group=prod
      - nacos:database.properties?group=prod
    activate:
      on-profile: dev
---
spring:
  config:
    import:
      - nacos:common.properties?group=prod
      - nacos:database.properties?group=prod
    activate:
      on-profile: test
---
spring:
  config:
    import:
      - nacos:common.properties?group=prod
      - nacos:database.properties?group=prod
    activate:
      on-profile: prod