spring:
  cloud:
    gateway:
      routes:
        - id: order-route
          uri: lb://service-order
          predicates:
            - name: Path
              args:
                patterns: /apr/order/**
                matchTrailingSlash: true
          order: 1 #数字越小优先级越高
          filters: #/api/order/ab/c -> /ab/c
            - RewritePath=/api/order?(?<segment>.*),/$\{segment}
            - OnceToken=X-Response-Token,uuid
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product?(?<segment>.*),/$\{segment}
        - id: bing-route
          uri: https://cn.bing.com
          predicates:
            - name: Path
              args:
                patterns: /search
                matchTrailingSlash: true
            - name: Query
              args:
                param: q
                regexp: haha
            - name: Vip
              args:
                param: user
                value: lyhn
      default-filters:
        - AddResponseHeader=X-Response-Abc,123 #默认filter